development:
  adapter: postgresql
  encoding: utf8
  database: team_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: team_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: team_production
  pool: 5
  username: 
  password:
