# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9514b7a858b239cbcdfbdacbfccd6891154f541aa85735f527c79ae7d858fb4cef975777033e7426c6b9b045d6691f6f1c0e864ef8b6e5ef499b9e6e4fd66e09

test:
  secret_key_base: aa9ea61e67ac483829054d2ded19fae66734f7a23b978043755de9f2848bb89e448823ddbb78c88edcef301b3fd5b6d74d3c048cd2e3bf5e66a5ec97db5817a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
